apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-deployment
  namespace: dev
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
        labels:
          app: polybot
    spec:
      containers:
      - name: server
        image: galgu/polybot2:d340fc41daa0ad81ca36945e836fedb74520d9ac
        ports:
        - containerPort: 8443 # Ensure this matches your application's listening port
---
apiVersion: v1
kind: Service
metadata:
  name: polybot2-service
  namespace: dev
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
